import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import * as url from "../utils/url";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form action={`${url.api}/start`} method="GET">
        <button type="submit">Start with Google</button>
      </form>
    </div>
  );
};

export default Home;
